apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  security:
    dataPlane:
      mtls: true
      automtls: true
    controlPlane:
      mtls: true
  tracing:
    type: Jaeger
    sampling: 10000  # 100% sampling for dev/demo; reduce for production
  addons:
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    grafana:
      enabled: true
    prometheus:
      enabled: true
  proxy:
    runtime:
      container:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
  runtime:
    defaults:
      container:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
