#!/bin/bash
# openshift-entrypoint-meet.sh
# Replaces s6-overlay for jitsi/web on CentOS Stream 10.
# Runs cont-init.d scripts in order, skipping any that use s6-overlay
# interpreters (execlineb, with-contenv) not present on CentOS.
set -e

echo "[entrypoint] Running cont-init.d config scripts..."
for script in $(ls /etc/cont-init.d/ | sort); do
    path="/etc/cont-init.d/${script}"
    shebang=$(head -1 "${path}" 2>/dev/null || true)
    # Skip timezone script — tries to chown /etc/localtime (needs root)
    if [ "${script}" = "01-set-timezone" ]; then
        echo "[entrypoint] ${script} (skipped - TZ set via env)"
        continue
    fi
    echo "[entrypoint] ${script}"
    if echo "${shebang}" | grep -qE "execlineb"; then
        echo "[entrypoint] ${script} (skipped - execlineb)"
        continue
    elif echo "${shebang}" | grep -q "with-contenv"; then
        # Strip apt-cache calls (Debian-only) before running via bash
        tmpscript=$(mktemp)
        sed             -e 's|.*apt-cache.*|: # apt-cache skipped (not Debian)|g'             -e 's|.*chown .*|: # chown skipped (OpenShift SCC)|g'             "${path}" > "${tmpscript}"
        # Run script; ignore chown/permission errors (files are already
        # owned correctly from Containerfile). Fail only on real errors.
        bash "${tmpscript}" || {
            rc=$?
            echo "[entrypoint] WARNING: ${script} exited with code ${rc} (likely chown — continuing)"
        }
        rm -f "${tmpscript}"
    elif [ -x "${path}" ]; then
        "${path}" || { echo "[entrypoint] ERROR: ${script} failed"; exit 1; }
    fi
done
echo "[entrypoint] Config complete. Starting nginx..."

# Use the nginx.conf generated by 10-config directly — it contains the
# full http{}/server{} structure with the correct Jitsi site config.
# The CentOS default nginx.conf includes conf.d at the wrong context level.
if [ -f /config/nginx/nginx.conf ]; then
    echo "[entrypoint] Using generated nginx.conf from /config/nginx/"
    # Fix pid path and user directive in generated config (written for Debian/root)
    # Patch user directive and pid in generated configs
    # (port remapping already done in /defaults templates at build time)
    find /config/nginx/ -name "*.conf" | while read cfg; do
        sed -i \
            -e 's|^user .*;||g' \
            -e 's|pid /run/nginx.pid|pid /tmp/nginx.pid|g' \
            -e 's|pid /var/run/nginx.pid|pid /tmp/nginx.pid|g' \
            "${cfg}"
    done
    echo "[entrypoint] Patched generated nginx configs"
    NGINX_CONF=/config/nginx/nginx.conf
else
    echo "[entrypoint] WARNING: /config/nginx/nginx.conf not found, using default"
    NGINX_CONF=/etc/nginx/nginx.conf
fi

# Test nginx config before starting
nginx -t -c "${NGINX_CONF}" 2>&1 || { echo "[entrypoint] ERROR: nginx config test failed"; exit 1; }

exec nginx -c "${NGINX_CONF}"
