apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: openemr
    app.kubernetes.io/runtime: mariadb
  name: mariadb-secret
  namespace: openemr
stringData:
  database-name: openemr
  database-password: wuq8OyNwj5k2ieqcg41gfYn5smgLN3BCWFPXWvwOg1n9Rdg9
  database-root-password: jiFXWgoTXh90zdvEXcwSkPxf6xU5eD5BpK7rVym3Ui4FdgFz
  database-user: openemr
type: Opaque
