apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: openemr
    app.kubernetes.io/runtime: mariadb
  name: mariadb-data
  namespace: openemr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
