apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openemr
    app.kubernetes.io/component: application
    app.kubernetes.io/name: openemr
    app.kubernetes.io/part-of: openemr
    app.kubernetes.io/runtime: php
  name: openemr-sites
  namespace: openemr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
