apiVersion: v1
kind: Secret
metadata:
  labels:
    app: openemr
    app.kubernetes.io/component: application
    app.kubernetes.io/name: openemr
    app.kubernetes.io/part-of: openemr
    app.kubernetes.io/runtime: php
  name: openemr-secret
  namespace: openemr
stringData:
  admin-password: wic1tXKtfyW6McMwjxd0PhXf
  admin-username: admin
type: Opaque
